name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - LICENSE.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - LICENSE.md
      - .gitignore

jobs:
  build:
    name: "Update Editor's Copy"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: "Setup"
        id: setup
        run: date -u "+date=%FT%T" >>"$GITHUB_OUTPUT"

      - name: "Caching"
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            .refcache
            .venv
            .gems
            node_modules
            .targets.mk
          key: i-d-${{ steps.setup.outputs.date }}
          restore-keys: i-d-

      - name: "Build Drafts"
        id: build
        uses: martinthomson/i-d-template@d2ce969b54014edf5671856b6866866c258bf8f5 # v1
        with:
          token: ${{ github.token }}

      - name: "Fix Lints"
        id: fix-lint
        if: always() && steps.build.outcome == 'failure'
        uses: martinthomson/i-d-template@d2ce969b54014edf5671856b6866866c258bf8f5 # v1
        with:
          make: fix-lint

      - name: "Propose Linting Fixes"
        if: >
          always() &&
          steps.fix-lint.outcome != 'skipped' &&
          github.event.pull_request &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: parkerbxyz/suggest-changes@e24c62a5a3235e6090721c7b0355b825a3a4ba9a # v3.1.2
        with:
          token: ${{ github.token }}

      - name: "Update GitHub Pages"
        uses: martinthomson/i-d-template@d2ce969b54014edf5671856b6866866c258bf8f5 # v1
        if: ${{ github.event_name == 'push' }}
        with:
          make: gh-pages
          token: ${{ github.token }}

      - name: "Archive Built Drafts"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: drafts
          path: |
            draft-*.html
            draft-*.txt
